# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-10 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20170710_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='content type')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='document_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Content types'),
        ),
        migrations.AddField(
            model_name='project',
            name='reading_amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='amount of reading'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='canonical',
            field=models.BooleanField(default=False, help_text='This Domain is the primary one where the documentation is served from.', verbose_name='Canonical'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='count',
            field=models.IntegerField(default=0, help_text='Number of times this domain has been hit.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='allow_promos',
            field=models.BooleanField(default=True, help_text='Allow sponsor advertisements on my project documentation', verbose_name='Sponsor advertisements'),
        ),
        migrations.AlterField(
            model_name='project',
            name='comment_moderation',
            field=models.BooleanField(default=False, verbose_name='Comment Moderation)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='requirements_file',
            field=models.CharField(blank=True, default=None, help_text='A <a href="https://pip.pypa.io/en/latest/user_guide.html#requirements-files"> pip requirements file</a> needed to build your documentation. Path from the root of your project.', max_length=255, null=True, verbose_name='Requirements file'),
        ),
    ]
